### ISSUE TITLE
Pin new grad positions and internships repositories

### ISSUE THREAD

**Issue by arunsathiya** [sharunkumar/sharunkumar#3]
<img width="1245" alt="image" src="https://github.com/sharunkumar/sharunkumar/assets/18581859/961ab237-cc67-40fc-8549-ef303d249aaa">

Pinned repositories seem outdated/old projects. Could update to these:

- https://github.com/sharunkumar/New-Grad-Positions
- https://github.com/sharunkumar/Summer2024-Internships

**Comment by sharunkumar** [comment]
Lol okay xD

**Comment by sharunkumar** [comment]
I didn't want to pin forks but at this point I have worked on them too much lol

**Comment by sharunkumar** [comment]
@arunsathiya 

![image](https://github.com/sharunkumar/sharunkumar/assets/715417/12c53a3d-e639-49dd-8c12-ab9286e5776b)

**Comment by sharunkumar** [comment]
~~I just realised that I don't have a description for janitor oops~~
